### ISSUE TITLE
Download Repository

### ISSUE THREAD

**Issue by tomatau** [Thinkful-Ed/karma-clone#9]
Originally we were showing students the complete karma clone and encouraging them to download from the half complete version so they could implement the extra features. This download link is still shared in the app.

https://github.com/Thinkful-Ed/startup-landing-page

It would be worth making sure that changes to styles the karma-clone repo are also reflected in the downloadable zip at the startup-landing-page clone repo.

**Comment by aric87** [comment]
@tomatau Is this still a relevant issue?

**Comment by tomatau** [comment]
Sounds good to close but I think you should do one last check that this download link doesn't still exist towards the end of the project in the curriculum. In the last few challenges/sections of the project it might be still provided as a solution.

**Comment by aric87** [comment]
1.5.2 in the curriculum does have the tnowalk version, but it's updated in preview and pulled into master. Thanks!
